apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'false'
  labels:
    app: gutiktok-comment-service
  name: gutiktok-comment-service
  namespace: gutiktok-service-bundle
spec:
  selector:
    matchLabels:
      name: gutiktok-comment-service
  template:
    metadata:
      labels:
        app: gutiktok-comment-service
        branch: master
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: gutiktok-comment-service
        dream-app: gutiktok-comment-service
        dream-unit: gutiktok-comment-service
    spec:
      imagePullSecrets:
        -   name: regcred
      containers:
        -   image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            name: gutiktok-comment-service
            command:
              - ./services/comment/CommentService
            envFrom:
              -   configMapRef:
                    name: env-config
              - configMapRef:
                  name: gutiktok-env
              - secretRef:
                  name: gutiktok-secret
            volumeMounts:
              - mountPath: /var/log/gutiktok
                name: log-volume
            ports:
              - name: grpc-37003
                containerPort: 37003
                protocol: TCP
              - name: metrics-37099
                containerPort: 37099
                protocol: TCP
            resources:
              limits:
                cpu: 2000m
                memory: 2048Mi
              requests:
                cpu: 100m
                memory: 128Mi
        - name: logger
          image: fluent/fluent-bit:1.8.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: config
            - mountPath: /var/log/gutiktok
              name: log-volume
      volumes:
        - name: config
          configMap:
            name: gutiktok-log-config
        - name: log-volume
          emptyDir: { }
      terminationGracePeriodSeconds: 30