apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'false'
  labels:
    app: gutiktok-auth-service
  name: gutiktok-auth-service
  namespace: gutiktok-service-bundle
spec:
  selector:
    matchLabels:
      name: gutiktok-auth-service
  template:
    metadata:
      labels:
        app: gutiktok-auth-service
        branch: master
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: gutiktok-auth-service
        dream-app: gutiktok-auth-service
        dream-unit: gutiktok-auth-service
    spec:
      imagePullSecrets:
        -  name: regcred
      containers:
        - image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: gutiktok-auth-service
          command:
            - ./services/auth/AuthService
          envFrom:
            - configMapRef:
                name: env-config
            - configMapRef:
                name: gutiktok-env
            - secretRef:
                name: gutiktok-secret
          ports:
            - name: grpc-37001
              containerPort: 37001
              protocol: TCP
            - name: metrics-37099
              containerPort: 37099
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/gutiktok
              name: log-volume
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - name: logger
          image: fluent/fluent-bit:1.8.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: config
            - mountPath: /var/log/gutiktok
              name: log-volume
      volumes:
        - name: config
          configMap:
            name: gutiktok-log-config
        - name: log-volume
          emptyDir: { }
      terminationGracePeriodSeconds: 30