apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'false'
  labels:
    app: gugotik-recommend-service
  name: gugotik-recommend-service
  namespace: gugotik-service-bundle
spec:
  selector:
    matchLabels:
      name: gugotik-recommend-service
  template:
    metadata:
      labels:
        app: gugotik-recommend-service
        branch: master
        version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
        name: gugotik-recommend-service
        dream-app: gugotik-recommend-service
        dream-unit: gugotik-recommend-service
    spec:
      imagePullSecrets:
        -   name: regcred
      containers:
        -   image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            name: gugotik-recommend-service
            command:
              - ./services/recommend/RecommendService
            envFrom:
              -   configMapRef:
                    name: env-config
              - configMapRef:
                  name: gugotik-env
              - secretRef:
                  name: gugotik-secret
            volumeMounts:
              - mountPath: /var/log/gugotik
                name: log-volume
            ports:
              - name: grpc-37009
                containerPort: 37009
                protocol: TCP
              - name: metrics-37099
                containerPort: 37099
                protocol: TCP
            resources:
              limits:
                cpu: 2000m
                memory: 2048Mi
              requests:
                cpu: 100m
                memory: 128Mi
        - name: logger
          image: fluent/fluent-bit:1.8.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: config
            - mountPath: /var/log/gugotik
              name: log-volume
      volumes:
        - name: config
          configMap:
            name: gugotik-log-config
        - name: log-volume
          emptyDir: { }
      terminationGracePeriodSeconds: 30