apiVersion: v1
kind: Service
metadata:
  labels:
    app: gutiktok-http-service
  name: gutiktok-http-service
  namespace: gutiktok-service-bundle
spec:
  ports:
    - name: http
      port: 37000
      protocol: TCP
      targetPort: 37000
  selector:
    name: gutiktok-http-service
    branch: master
  type: ClusterIP