jwtsecret: XFjLpUqzPbbSUHlLw
loggerWithTraceState: enable
mysql:
    logLevel: info
    charset: utf8mb4
    database: gutiktok
    host: 127.0.0.1
    password: root
    port: 3306
    username: root

log:
    enable: true
    level : info
    name: data/log/log.log
    MaxSize: 10
    MaxBackups: 5
    MaxAge: 28
    compress: false

redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    db: 3
