jwtsecret: XFjLpUqzPbbSUHlLw
consul:
    consulAnonymityPrefix: CONSUL_ANONYMITY_NAME
server:
    IP: 127.0.0.1:8500
    address: 127.0.0.1
    https: false
    certFile:
    keyFile:
tracers:
    OtelState: disable
    addr: 127.0.0.1
    OtelSampler: 0.01
mysql:
    logLevel: info
    charset: utf8mb4
    database: gutiktok
    host: 127.0.0.1
    password: root
    port: 3306
    username: root
MysqlReplica:
    MySQLReplicaState: disable
    MySQLReplicaAddress: 127.0.0.1,127.0.0.1
    MySQLReplicaUsername: root
    MySQLReplicaPassword: 123456
log:
    enable: true
    level : info
    loggerWithTraceState: enable
    name: data/log/log.log
    MaxSize: 10
    MaxBackups: 5
    MaxAge: 28
    compress: false

redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    db: 3
