jwtsecret: XFjLpUqzPbbSUHlLw
mysql:
    charset: utf8mb4
    database: gutiktok
    host: 127.0.0.1
    password: root
    port: 3306
    username: root

log:
    enable: true
    level : info
    name: data/log/log.log
    max_size: 10
    "max_backups": 5
    "max_age": 28
    "compress": false

redis:
    host: 127.0.0.1
    port: 6379
    password:
    db: 3
